[2024-06-14T05:52:08.663+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T05:52:08.701+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T05:52:08.712+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T05:52:08.713+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-14T05:52:08.729+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2024-06-13 00:00:00+00:00
[2024-06-14T05:52:08.735+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpw9286nn2']
[2024-06-14T05:52:08.738+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask python_job
[2024-06-14T05:52:08.738+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=490) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-14T05:52:08.739+0000] {standard_task_runner.py:63} INFO - Started process 491 to run task
[2024-06-14T05:52:08.790+0000] {task_command.py:426} INFO - Running <TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [running]> on host cf5928e4c8ca
[2024-06-14T05:52:08.874+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-14T05:52:08.876+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T05:52:08.897+0000] {spark_submit.py:204} INFO - Could not load connection string spark-conn, defaulting to yarn
[2024-06-14T05:52:08.899+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py
[2024-06-14T05:52:08.971+0000] {spark_submit.py:488} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-14T05:52:10.599+0000] {spark_submit.py:488} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-06-14T05:52:10.600+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-06-14T05:52:10.601+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-06-14T05:52:10.602+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-06-14T05:52:10.603+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-06-14T05:52:10.603+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2024-06-14T05:52:10.604+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2024-06-14T05:52:10.605+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-06-14T05:52:10.605+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-06-14T05:52:10.606+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-06-14T05:52:10.607+0000] {spark_submit.py:488} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-06-14T05:52:10.618+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T05:52:10.629+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.
[2024-06-14T05:52:10.639+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, run_id=scheduled__2024-06-13T00:00:00+00:00, execution_date=20240613T000000, start_date=20240614T055208, end_date=20240614T055210
[2024-06-14T05:52:10.652+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task python_job (Cannot execute: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.; 491)
[2024-06-14T05:52:10.683+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T05:52:10.703+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T05:52:10.710+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-14T07:29:11.273+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T07:29:11.311+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T07:29:11.324+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T07:29:11.325+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-14T07:29:11.340+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2024-06-13 00:00:00+00:00
[2024-06-14T07:29:11.347+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmp0vhfj3mi']
[2024-06-14T07:29:11.349+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=684) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-14T07:29:11.350+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask python_job
[2024-06-14T07:29:11.351+0000] {standard_task_runner.py:63} INFO - Started process 690 to run task
[2024-06-14T07:29:11.401+0000] {task_command.py:426} INFO - Running <TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [running]> on host e342e0ac560c
[2024-06-14T07:29:11.486+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Selva' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-14T07:29:11.487+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T07:29:11.510+0000] {spark_submit.py:271} INFO - Could not load connection string spark-conn, defaulting to yarn
[2024-06-14T07:29:11.512+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py
[2024-06-14T07:29:11.590+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-14T07:29:13.241+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-06-14T07:29:13.241+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-06-14T07:29:13.242+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-06-14T07:29:13.243+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-06-14T07:29:13.243+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-06-14T07:29:13.244+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2024-06-14T07:29:13.245+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2024-06-14T07:29:13.246+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-06-14T07:29:13.246+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-06-14T07:29:13.247+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-06-14T07:29:13.247+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-06-14T07:29:13.260+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T07:29:13.271+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.
[2024-06-14T07:29:13.278+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, run_id=scheduled__2024-06-13T00:00:00+00:00, execution_date=20240613T000000, start_date=20240614T072911, end_date=20240614T072913
[2024-06-14T07:29:13.296+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task python_job (Cannot execute: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.; 690)
[2024-06-14T07:29:13.334+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T07:29:13.356+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T07:29:13.362+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-14T09:03:18.951+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T09:03:19.097+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T09:03:19.136+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T09:03:19.139+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-14T09:03:19.179+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2024-06-13 00:00:00+00:00
[2024-06-14T09:03:19.198+0000] {standard_task_runner.py:63} INFO - Started process 222 to run task
[2024-06-14T09:03:19.206+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpdp22zqjk']
[2024-06-14T09:03:19.211+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask python_job
[2024-06-14T09:03:19.480+0000] {task_command.py:426} INFO - Running <TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [running]> on host 3e8885418805
[2024-06-14T09:03:19.973+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Selva' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-14T09:03:19.978+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T09:03:20.181+0000] {base.py:84} INFO - Using connection ID 'spark-conn' for task execution.
[2024-06-14T09:03:20.192+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7707 --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py
[2024-06-14T09:03:20.808+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-14T09:03:32.191+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO SparkContext: Running Spark version 3.5.1
[2024-06-14T09:03:32.195+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-06-14T09:03:32.196+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO SparkContext: Java version 17.0.11
[2024-06-14T09:03:32.326+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-06-14T09:03:32.552+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO ResourceUtils: ==============================================================
[2024-06-14T09:03:32.554+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-06-14T09:03:32.555+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO ResourceUtils: ==============================================================
[2024-06-14T09:03:32.556+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO SparkContext: Submitted application: PythonWordCount
[2024-06-14T09:03:32.617+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-06-14T09:03:32.635+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO ResourceProfile: Limiting resource is cpu
[2024-06-14T09:03:32.637+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-06-14T09:03:32.804+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO SecurityManager: Changing view acls to: ***
[2024-06-14T09:03:32.805+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO SecurityManager: Changing modify acls to: ***
[2024-06-14T09:03:32.806+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO SecurityManager: Changing view acls groups to:
[2024-06-14T09:03:32.808+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO SecurityManager: Changing modify acls groups to:
[2024-06-14T09:03:32.809+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:32 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-06-14T09:03:33.423+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:33 INFO Utils: Successfully started service 'sparkDriver' on port 42887.
[2024-06-14T09:03:33.529+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:33 INFO SparkEnv: Registering MapOutputTracker
[2024-06-14T09:03:33.631+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:33 INFO SparkEnv: Registering BlockManagerMaster
[2024-06-14T09:03:33.665+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:33 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-06-14T09:03:33.667+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:33 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-06-14T09:03:33.673+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:33 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-06-14T09:03:33.724+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:33 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-68a97f67-12db-4068-84e6-2332a56827a8
[2024-06-14T09:03:33.749+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:33 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-06-14T09:03:33.785+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:33 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-06-14T09:03:34.084+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:34 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-06-14T09:03:34.331+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:34 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-06-14T09:03:34.896+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:34 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7707...
[2024-06-14T09:03:35.124+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:35 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark-master:7707
[2024-06-14T09:03:35.125+0000] {spark_submit.py:571} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-06-14T09:03:35.126+0000] {spark_submit.py:571} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-06-14T09:03:35.126+0000] {spark_submit.py:571} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-06-14T09:03:35.127+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-06-14T09:03:35.128+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-06-14T09:03:35.129+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-06-14T09:03:35.130+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-06-14T09:03:35.131+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-06-14T09:03:35.132+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-06-14T09:03:35.135+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-06-14T09:03:35.136+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-06-14T09:03:35.138+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-06-14T09:03:35.138+0000] {spark_submit.py:571} INFO - Caused by: java.io.IOException: Failed to connect to spark-master/172.20.0.3:7707
[2024-06-14T09:03:35.139+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-06-14T09:03:35.139+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-06-14T09:03:35.140+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-06-14T09:03:35.140+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-06-14T09:03:35.141+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-06-14T09:03:35.141+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-06-14T09:03:35.142+0000] {spark_submit.py:571} INFO - ... 4 more
[2024-06-14T09:03:35.142+0000] {spark_submit.py:571} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: spark-master/172.20.0.3:7707
[2024-06-14T09:03:35.143+0000] {spark_submit.py:571} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-06-14T09:03:35.144+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-06-14T09:03:35.144+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-06-14T09:03:35.145+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2024-06-14T09:03:35.146+0000] {spark_submit.py:571} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-06-14T09:03:35.147+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-06-14T09:03:35.152+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-06-14T09:03:35.154+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-06-14T09:03:35.154+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-06-14T09:03:35.155+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-06-14T09:03:35.155+0000] {spark_submit.py:571} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-06-14T09:03:35.156+0000] {spark_submit.py:571} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-06-14T09:03:35.157+0000] {spark_submit.py:571} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-06-14T09:03:35.158+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-06-14T09:03:54.895+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:54 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7707...
[2024-06-14T09:03:54.899+0000] {spark_submit.py:571} INFO - 24/06/14 09:03:54 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark-master:7707
[2024-06-14T09:03:54.900+0000] {spark_submit.py:571} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-06-14T09:03:54.901+0000] {spark_submit.py:571} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-06-14T09:03:54.902+0000] {spark_submit.py:571} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-06-14T09:03:54.902+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-06-14T09:03:54.903+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-06-14T09:03:54.903+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-06-14T09:03:54.904+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-06-14T09:03:54.904+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-06-14T09:03:54.905+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-06-14T09:03:54.906+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-06-14T09:03:54.906+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-06-14T09:03:54.907+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-06-14T09:03:54.907+0000] {spark_submit.py:571} INFO - Caused by: java.io.IOException: Failed to connect to spark-master/172.20.0.3:7707
[2024-06-14T09:03:54.907+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-06-14T09:03:54.908+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-06-14T09:03:54.908+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-06-14T09:03:54.908+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-06-14T09:03:54.909+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-06-14T09:03:54.909+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-06-14T09:03:54.909+0000] {spark_submit.py:571} INFO - ... 4 more
[2024-06-14T09:03:54.909+0000] {spark_submit.py:571} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: spark-master/172.20.0.3:7707
[2024-06-14T09:03:54.910+0000] {spark_submit.py:571} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-06-14T09:03:54.910+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-06-14T09:03:54.910+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-06-14T09:03:54.910+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2024-06-14T09:03:54.911+0000] {spark_submit.py:571} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-06-14T09:03:54.911+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-06-14T09:03:54.911+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-06-14T09:03:54.911+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-06-14T09:03:54.911+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-06-14T09:03:54.912+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-06-14T09:03:54.912+0000] {spark_submit.py:571} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-06-14T09:03:54.912+0000] {spark_submit.py:571} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-06-14T09:03:54.912+0000] {spark_submit.py:571} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-06-14T09:03:54.912+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-06-14T09:04:14.898+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:14 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7707...
[2024-06-14T09:04:14.905+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:14 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark-master:7707
[2024-06-14T09:04:14.906+0000] {spark_submit.py:571} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-06-14T09:04:14.907+0000] {spark_submit.py:571} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-06-14T09:04:14.908+0000] {spark_submit.py:571} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-06-14T09:04:14.908+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-06-14T09:04:14.909+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-06-14T09:04:14.909+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-06-14T09:04:14.910+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-06-14T09:04:14.911+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-06-14T09:04:14.911+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-06-14T09:04:14.912+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-06-14T09:04:14.912+0000] {spark_submit.py:571} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-06-14T09:04:14.913+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-06-14T09:04:14.913+0000] {spark_submit.py:571} INFO - Caused by: java.io.IOException: Failed to connect to spark-master/172.20.0.3:7707
[2024-06-14T09:04:14.914+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-06-14T09:04:14.915+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-06-14T09:04:14.915+0000] {spark_submit.py:571} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-06-14T09:04:14.915+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-06-14T09:04:14.916+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-06-14T09:04:14.916+0000] {spark_submit.py:571} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-06-14T09:04:14.917+0000] {spark_submit.py:571} INFO - ... 4 more
[2024-06-14T09:04:14.917+0000] {spark_submit.py:571} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: spark-master/172.20.0.3:7707
[2024-06-14T09:04:14.917+0000] {spark_submit.py:571} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-06-14T09:04:14.917+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-06-14T09:04:14.917+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-06-14T09:04:14.918+0000] {spark_submit.py:571} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2024-06-14T09:04:14.918+0000] {spark_submit.py:571} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-06-14T09:04:14.918+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-06-14T09:04:14.918+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-06-14T09:04:14.919+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-06-14T09:04:14.919+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-06-14T09:04:14.919+0000] {spark_submit.py:571} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-06-14T09:04:14.920+0000] {spark_submit.py:571} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-06-14T09:04:14.920+0000] {spark_submit.py:571} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-06-14T09:04:14.921+0000] {spark_submit.py:571} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-06-14T09:04:14.921+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-06-14T09:04:34.903+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:34 ERROR StandaloneSchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
[2024-06-14T09:04:34.905+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:34 WARN StandaloneSchedulerBackend: Application ID is not initialized yet.
[2024-06-14T09:04:34.923+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:34 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36959.
[2024-06-14T09:04:34.924+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:34 INFO NettyBlockTransferService: Server created on 3e8885418805:36959
[2024-06-14T09:04:34.926+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:34 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-06-14T09:04:34.936+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:34 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 3e8885418805, 36959, None)
[2024-06-14T09:04:34.941+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:34 INFO BlockManagerMasterEndpoint: Registering block manager 3e8885418805:36959 with 434.4 MiB RAM, BlockManagerId(driver, 3e8885418805, 36959, None)
[2024-06-14T09:04:34.944+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:34 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 3e8885418805, 36959, None)
[2024-06-14T09:04:34.946+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:34 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 3e8885418805, 36959, None)
[2024-06-14T09:04:35.144+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-06-14T09:04:35.436+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-06-14T09:04:35.449+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO SparkUI: Stopped Spark web UI at http://3e8885418805:4040
[2024-06-14T09:04:35.453+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-06-14T09:04:35.457+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-06-14T09:04:35.463+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 WARN StandaloneAppClient$ClientEndpoint: Drop UnregisterApplication(null) because has not yet connected to master
[2024-06-14T09:04:35.474+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-06-14T09:04:35.491+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO MemoryStore: MemoryStore cleared
[2024-06-14T09:04:35.492+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO BlockManager: BlockManager stopped
[2024-06-14T09:04:35.499+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-06-14T09:04:35.501+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-06-14T09:04:35.511+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO SparkContext: Successfully stopped SparkContext
[2024-06-14T09:04:35.533+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2024-06-14T09:04:35.534+0000] {spark_submit.py:571} INFO - File "/opt/***/jobs/python/wordcountjob.py", line 7, in <module>
[2024-06-14T09:04:35.535+0000] {spark_submit.py:571} INFO - words = spark.sparkContext.parallelize(text.split(" "))
[2024-06-14T09:04:35.536+0000] {spark_submit.py:571} INFO - ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-06-14T09:04:35.536+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 824, in parallelize
[2024-06-14T09:04:35.537+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 870, in _serialize_to_jvm
[2024-06-14T09:04:35.537+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/context.py", line 818, in reader_func
[2024-06-14T09:04:35.537+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-06-14T09:04:35.537+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-06-14T09:04:35.538+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-06-14T09:04:35.539+0000] {spark_submit.py:571} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.readRDDFromFile.
[2024-06-14T09:04:35.539+0000] {spark_submit.py:571} INFO - : java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
[2024-06-14T09:04:35.540+0000] {spark_submit.py:571} INFO - This stopped SparkContext was created at:
[2024-06-14T09:04:35.540+0000] {spark_submit.py:571} INFO - 
[2024-06-14T09:04:35.540+0000] {spark_submit.py:571} INFO - org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-06-14T09:04:35.541+0000] {spark_submit.py:571} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-06-14T09:04:35.541+0000] {spark_submit.py:571} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2024-06-14T09:04:35.541+0000] {spark_submit.py:571} INFO - java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-06-14T09:04:35.541+0000] {spark_submit.py:571} INFO - java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2024-06-14T09:04:35.541+0000] {spark_submit.py:571} INFO - java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[2024-06-14T09:04:35.542+0000] {spark_submit.py:571} INFO - py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-06-14T09:04:35.542+0000] {spark_submit.py:571} INFO - py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-06-14T09:04:35.542+0000] {spark_submit.py:571} INFO - py4j.Gateway.invoke(Gateway.java:238)
[2024-06-14T09:04:35.542+0000] {spark_submit.py:571} INFO - py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-06-14T09:04:35.542+0000] {spark_submit.py:571} INFO - py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-06-14T09:04:35.543+0000] {spark_submit.py:571} INFO - py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-06-14T09:04:35.543+0000] {spark_submit.py:571} INFO - py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-06-14T09:04:35.543+0000] {spark_submit.py:571} INFO - java.base/java.lang.Thread.run(Thread.java:840)
[2024-06-14T09:04:35.543+0000] {spark_submit.py:571} INFO - 
[2024-06-14T09:04:35.543+0000] {spark_submit.py:571} INFO - The currently active SparkContext was created at:
[2024-06-14T09:04:35.544+0000] {spark_submit.py:571} INFO - 
[2024-06-14T09:04:35.544+0000] {spark_submit.py:571} INFO - org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2024-06-14T09:04:35.544+0000] {spark_submit.py:571} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2024-06-14T09:04:35.544+0000] {spark_submit.py:571} INFO - java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2024-06-14T09:04:35.544+0000] {spark_submit.py:571} INFO - java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2024-06-14T09:04:35.545+0000] {spark_submit.py:571} INFO - java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[2024-06-14T09:04:35.545+0000] {spark_submit.py:571} INFO - java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[2024-06-14T09:04:35.545+0000] {spark_submit.py:571} INFO - py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2024-06-14T09:04:35.546+0000] {spark_submit.py:571} INFO - py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-06-14T09:04:35.546+0000] {spark_submit.py:571} INFO - py4j.Gateway.invoke(Gateway.java:238)
[2024-06-14T09:04:35.546+0000] {spark_submit.py:571} INFO - py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2024-06-14T09:04:35.546+0000] {spark_submit.py:571} INFO - py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2024-06-14T09:04:35.546+0000] {spark_submit.py:571} INFO - py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-06-14T09:04:35.547+0000] {spark_submit.py:571} INFO - py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-06-14T09:04:35.547+0000] {spark_submit.py:571} INFO - java.base/java.lang.Thread.run(Thread.java:840)
[2024-06-14T09:04:35.547+0000] {spark_submit.py:571} INFO - 
[2024-06-14T09:04:35.548+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.assertNotStopped(SparkContext.scala:122)
[2024-06-14T09:04:35.548+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.$anonfun$parallelize$1(SparkContext.scala:942)
[2024-06-14T09:04:35.548+0000] {spark_submit.py:571} INFO - at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2024-06-14T09:04:35.548+0000] {spark_submit.py:571} INFO - at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2024-06-14T09:04:35.549+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.withScope(SparkContext.scala:924)
[2024-06-14T09:04:35.549+0000] {spark_submit.py:571} INFO - at org.apache.spark.SparkContext.parallelize(SparkContext.scala:941)
[2024-06-14T09:04:35.549+0000] {spark_submit.py:571} INFO - at org.apache.spark.api.java.JavaRDD$.readRDDFromInputStream(JavaRDD.scala:259)
[2024-06-14T09:04:35.549+0000] {spark_submit.py:571} INFO - at org.apache.spark.api.java.JavaRDD$.readRDDFromFile(JavaRDD.scala:239)
[2024-06-14T09:04:35.549+0000] {spark_submit.py:571} INFO - at org.apache.spark.api.python.PythonRDD$.readRDDFromFile(PythonRDD.scala:289)
[2024-06-14T09:04:35.550+0000] {spark_submit.py:571} INFO - at org.apache.spark.api.python.PythonRDD.readRDDFromFile(PythonRDD.scala)
[2024-06-14T09:04:35.550+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-06-14T09:04:35.550+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-06-14T09:04:35.550+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-06-14T09:04:35.551+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[2024-06-14T09:04:35.551+0000] {spark_submit.py:571} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-06-14T09:04:35.551+0000] {spark_submit.py:571} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-06-14T09:04:35.551+0000] {spark_submit.py:571} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-06-14T09:04:35.551+0000] {spark_submit.py:571} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-06-14T09:04:35.552+0000] {spark_submit.py:571} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-06-14T09:04:35.552+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-06-14T09:04:35.552+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-06-14T09:04:35.552+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-06-14T09:04:35.552+0000] {spark_submit.py:571} INFO - 
[2024-06-14T09:04:35.597+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO ShutdownHookManager: Shutdown hook called
[2024-06-14T09:04:35.597+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-6b95f34c-0354-4be8-80f9-d615cd7d2030/pyspark-d4ae5048-df33-4a9b-8b73-6e45c1beb4b4
[2024-06-14T09:04:35.603+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-6b95f34c-0354-4be8-80f9-d615cd7d2030
[2024-06-14T09:04:35.609+0000] {spark_submit.py:571} INFO - 24/06/14 09:04:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-99974f1f-c694-4bb7-b77d-9cd643701b6b
[2024-06-14T09:04:35.643+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T09:04:35.790+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7707 --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.
[2024-06-14T09:04:35.800+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, run_id=scheduled__2024-06-13T00:00:00+00:00, execution_date=20240613T000000, start_date=20240614T090319, end_date=20240614T090435
[2024-06-14T09:04:35.815+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task python_job (Cannot execute: spark-submit --master spark://spark-master:7707 --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.; 222)
[2024-06-14T09:04:35.840+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T09:04:35.860+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T09:04:35.867+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-14T12:10:02.459+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T12:10:02.491+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T12:10:02.500+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T12:10:02.501+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-14T12:10:02.516+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2024-06-13 00:00:00+00:00
[2024-06-14T12:10:02.521+0000] {standard_task_runner.py:63} INFO - Started process 291 to run task
[2024-06-14T12:10:02.525+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmphbs3buey']
[2024-06-14T12:10:02.528+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask python_job
[2024-06-14T12:10:02.583+0000] {task_command.py:426} INFO - Running <TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [running]> on host 16dec0d41d9e
[2024-06-14T12:10:02.671+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Selva' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-14T12:10:02.672+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T12:10:02.695+0000] {spark_submit.py:271} INFO - Could not load connection string spark-conn, defaulting to yarn
[2024-06-14T12:10:02.696+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py
[2024-06-14T12:10:02.768+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.11/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-14T12:10:05.229+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2024-06-14T12:10:05.230+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2024-06-14T12:10:05.230+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2024-06-14T12:10:05.231+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2024-06-14T12:10:05.232+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2024-06-14T12:10:05.232+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1103)
[2024-06-14T12:10:05.233+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1103)
[2024-06-14T12:10:05.233+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2024-06-14T12:10:05.234+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-06-14T12:10:05.234+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-06-14T12:10:05.234+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-06-14T12:10:05.249+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T12:10:05.541+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.
[2024-06-14T12:10:05.558+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, run_id=scheduled__2024-06-13T00:00:00+00:00, execution_date=20240613T000000, start_date=20240614T121002, end_date=20240614T121005
[2024-06-14T12:10:05.585+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task python_job (Cannot execute: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.; 291)
[2024-06-14T12:10:05.641+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T12:10:05.691+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T12:10:05.697+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
