[2024-06-14T08:23:56.922+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T08:23:56.960+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T08:23:56.972+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [queued]>
[2024-06-14T08:23:56.973+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-06-14T08:23:56.991+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2024-06-13 00:00:00+00:00
[2024-06-14T08:23:56.998+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'scheduled__2024-06-13T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpi8h69p7b']
[2024-06-14T08:23:57.002+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask python_job
[2024-06-14T08:23:57.002+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1756) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-14T08:23:57.003+0000] {standard_task_runner.py:63} INFO - Started process 1757 to run task
[2024-06-14T08:23:57.054+0000] {task_command.py:426} INFO - Running <TaskInstance: sparking_flow.python_job scheduled__2024-06-13T00:00:00+00:00 [running]> on host e342e0ac560c
[2024-06-14T08:23:57.140+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Selva' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-13T00:00:00+00:00'
[2024-06-14T08:23:57.142+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T08:23:57.163+0000] {base.py:84} INFO - Using connection ID 'spark-conn' for task execution.
[2024-06-14T08:23:57.164+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master-1:7077 --name arrow-spark --deploy-mode cluster jobs/python/wordcountjob.py
[2024-06-14T08:23:57.229+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-06-14T08:23:58.710+0000] {spark_submit.py:571} INFO - Exception in thread "main" org.apache.spark.SparkException: Cluster deploy mode is currently not supported for python applications on standalone clusters.
[2024-06-14T08:23:58.711+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.error(SparkSubmit.scala:1047)
[2024-06-14T08:23:58.712+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:293)
[2024-06-14T08:23:58.713+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:964)
[2024-06-14T08:23:58.713+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
[2024-06-14T08:23:58.714+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
[2024-06-14T08:23:58.715+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
[2024-06-14T08:23:58.715+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
[2024-06-14T08:23:58.716+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
[2024-06-14T08:23:58.717+0000] {spark_submit.py:571} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2024-06-14T08:23:58.730+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T08:23:58.741+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master-1:7077 --name arrow-spark --deploy-mode cluster jobs/python/wordcountjob.py. Error code is: 1.
[2024-06-14T08:23:58.746+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, run_id=scheduled__2024-06-13T00:00:00+00:00, execution_date=20240613T000000, start_date=20240614T082356, end_date=20240614T082358
[2024-06-14T08:23:58.760+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task python_job (Cannot execute: spark-submit --master spark://spark-master-1:7077 --name arrow-spark --deploy-mode cluster jobs/python/wordcountjob.py. Error code is: 1.; 1757)
[2024-06-14T08:23:58.787+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-14T08:23:58.808+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T08:23:58.814+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
